baseURL = 'https://www.tirupatibalan.com/'
copyright = "2010 - {year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-us'
theme = 'lowkey'
title = 'Tirupati Balan'
enableRobotsTXT = true
googleAnalytics = "G-WH639WR6N5"

# List Config
summaryLength= 15
paginate = 5

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'xcode-dark'
    tabWidth = 4
