[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "x.com/tirupati17"
    weight = 1

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/tirupati17"
    weight = 3