# Dependencies
markdown:          kramdown
highlighter:       rouge

# Setup
title:             Tirupati Balan
tagline:           'Personal Blog'
description:       'An iOS Developer and Internet Entrepreneur. Founder at <a href="http://celerstudio.com" target="_blank">Celerstudio</a>.'
url:               http://www.tirupatibalan.com
baseurl:           # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

google_analytics: UA-31207525-1
owner:
  name:           Tirupati Balan
  
author:
  name:            'Andrew Fong'
  url:             https://twitter.com/fongandrewc

paginate:          5
# paginate_path:   '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
disqus:
  shortname:       tirupatibalan

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-watch

# Custom vars
appstore_icon:     https://png.icons8.com/apple-app-store/dusk/50/000000
playstore_icon:    https://png.icons8.com/google-play/dusk/40/000000
website_icon:      https://png.icons8.com/website/dusk/40/000000
version:           3.4.1
sidebar_home_link: true
sidebar_photography_link: true

# sidebar_blog_link: '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:            https://github.com/tirupati17

#Jekyll-Photo-Gallery Settings
exiftag:
 sources:
   - images/photography #Set to location of photos

#MiniMagick
#https://github.com/zroger/jekyll-minimagick
mini_magick:
    photography:
        source: images/photography
        destination: images/photography/thumbnails
        resize: "1280x720"
    headers:
        source: images/headers
        destination: images/headers/thumbnails
        resize: "400x250"
        
atom:
  buildCommand:
    - jekyll
    - build
    - --option
    - --this
  buildEnv:
    JEKYLL_ENV: development
  postDirs:
    - _newsletters
  defaultPostDir: _drafts

defaults:
  -
    scope:
      path: "travels"
    values:
      permalink: /:path/:basename:output_ext